'use client';

import Link from 'next/link';
import { ArrowRight, Check, CircleHelp, Clock3, Gift, ShieldCheck, Sparkles } from 'lucide-react';
import { usePortal } from '@/components/portal-context';
import { formatUZS } from '@/lib/domain/pricing';
import { calculateLoyaltySummary } from '@/lib/domain/loyalty';
import { PageHeading, LoyaltyProgress, TierBadge } from '@/components/ui';

export default function LoyaltyPage() {
  const { config, customerBoxes, customerTurnover } = usePortal();
  const currentValue = config.metric === 'boxes' ? customerBoxes : customerTurnover;
  const summary = calculateLoyaltySummary(currentValue, config);
  const tiers = config.tiers.filter((tier) => tier.active).slice().sort((a, b) => a.minValue - b.minValue);
  return <>
    <PageHeading eyebrow="SIZNING HAMKORLIK IMTIYOZLARINGIZ" title="Sodiqlik dasturi" description="Ko‘proq xarid qiling — yuqori daraja va yanada manfaatli ulgurji narxlarga ega bo‘ling." actions={<Link href="/catalog" className="button primary">Xaridni boshlash <ArrowRight size={15} /></Link>} />
    {!config.enabled ? <div className="loyalty-paused-notice"><CircleHelp size={16} /><span><b>Sodiqlik dasturi vaqtincha to‘xtatilgan.</b> Hozirda daraja chegirmalari qo‘llanmaydi.</span></div> : null}
    <section className="loyalty-hero-card"><div className="loyalty-hero-glow" /><div className="loyalty-hero-top"><div><span className="section-kicker">JORIY DARAJANGIZ</span><div className="loyalty-current"><TierBadge tier={summary.currentTier} size="large" /><span className="loyalty-discount-number">{summary.discountPercent}<small>% chegirma</small></span></div></div><div className="loyalty-period-chip"><Clock3 size={14} /> {config.period === 'calendar-month' ? 'Joriy oy · 1–30 sentabr' : config.period === 'last-30-days' ? 'Oxirgi 30 kun' : 'Oxirgi 90 kun'}</div></div><div className="loyalty-hero-progress"><div className="progress-title"><b>{summary.currentValue.toLocaleString('uz-UZ')} {config.metric === 'boxes' ? 'quti' : 'so‘m'}</b><span>{summary.nextTier ? `${summary.nextTier.name} darajasiga ${summary.remaining.toLocaleString('uz-UZ')} ${config.metric === 'boxes' ? 'quti' : 'so‘m'} qoldi` : 'Siz eng yuqori darajadasiz'}</span></div><LoyaltyProgress summary={summary} /><div className="loyalty-next-tier"><span><Sparkles size={15} /> KEYINGI DARAJA</span><b>{summary.nextTier?.name ?? 'VIP'} <small>· {summary.nextTier?.discountPercent ?? summary.discountPercent}% chegirma</small></b></div></div></section>
    <div className="loyalty-explainer-row"><div className="loyalty-explainer"><span className="explainer-icon"><ShieldCheck size={17} /></span><span><b>Shaffof hisob-kitob</b><small>Faqat yetkazilgan va tasdiqlangan xaridlar hisoblanadi.</small></span></div><div className="loyalty-explainer"><span className="explainer-icon purple"><Sparkles size={17} /></span><span><b>Daraja darhol yangilanadi</b><small>Keyingi chegaraga yetgan zahoti yangi chegirma faollashadi.</small></span></div><div className="loyalty-explainer"><span className="explainer-icon amber"><Gift size={17} /></span><span><b>Shaxsiy kelishuv narxlari</b><small>Maxsus kelishilgan narxlar sodiqlik chegirmasidan ustun.</small></span></div></div>
    <section className="surface tier-table-card"><div className="section-header"><div><div className="section-kicker">BARCHA DARAJALAR</div><h3>Hamkorlik bosqichlari</h3><p>Har bir daraja ko‘proq tejash imkonini beradi.</p></div><span className="tier-count">{tiers.length} ta bosqich</span></div><div className="tier-table-list">{tiers.map((tier, index) => { const current = tier.id === summary.currentTier.id; const passed = currentValue >= tier.minValue; return <div className={`tier-table-row ${current ? 'current' : ''}`} key={tier.id}><span className="tier-step-index" style={{ '--tier-color': tier.color } as React.CSSProperties}>{passed ? <Check size={14} /> : `0${index + 1}`}</span><span className="tier-table-name"><TierBadge tier={tier} /><small>{tier.description}</small></span><span className="tier-threshold">{tier.minValue === 0 ? 'Boshlang‘ich' : `${tier.minValue.toLocaleString('uz-UZ')} ${config.metric === 'boxes' ? 'quti' : 'so‘m'} dan`}</span><span className="tier-rate">{tier.discountPercent}<small>%</small></span><span className={`tier-row-state ${current ? 'is-current' : passed ? 'is-passed' : ''}`}>{current ? 'Sizning darajangiz' : passed ? 'Erishildi' : 'Keyingi'}</span></div>; })}</div><div className="tier-table-foot"><CircleHelp size={15} /><span>Daraja har oyda hisoblanadi. Yuqori daraja darhol faollashadi, pasayish esa keyingi davr boshida qo‘llanadi.</span></div></section>
    <div className="loyalty-bottom"><div><span className="bottom-spark"><Sparkles size={17} /></span><span><b>{summary.nextTier ? `${config.metric === 'boxes' ? `${summary.remaining} quti` : formatUZS(summary.remaining)} xarid qilib, ${summary.nextTier.name}ga chiqing` : 'Siz VIP hamkorsiz'}</b><small>{summary.nextTier ? `${summary.nextTier.discountPercent}% chegirma — keyingi bosqichda sizni kutmoqda.` : 'Eng yuqori chegirma va shaxsiy hamkorlik shartlari siz uchun faol.'}</small></span></div><Link href="/catalog" className="button dark-button">Katalogga o‘tish <ArrowRight size={15} /></Link></div>
  </>;
}
